name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@master
    - name: build
      run: |
        mkdir build
        cmake -GXcode ..
        cmake --build .
    - name: test
      run: ctest
