name: marlin-kids

on: [push]

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@master
    - name: mac build
      run: |
        mkdir build
        cd build
        cmake -GXcode ..
        cmake --build .
    - name: ios build
      run: |
        mkdir build.ios
        cd build.ios
        cmake -GXcode -DCMAKE_TOOLCHAIN_FILE=../cmake/ios.toolchain.cmake -DPLATFORM=OS64 ..
        cmake --build .
    - name: test
      run: |
        cd build
        ctest
